example
exampleSize: maxSize numberItems: numberItems speedRatio: ratio
	"self exampleSize: 3 numberItems: 8 speedRatio: 3"
	"self exampleSize: 3 numberItems: 8 speedRatio: 1/3"

	"self switchToEnabled: true"	"to switch to enable selectors activity."
	"self switchToEnabled: false"	"to switch back to EmptyBoundedBuffer naive definition."

	super exampleSize: maxSize numberItems: numberItems speedRatio: ratio